### ISSUE TITLE
Remove the package updating details

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#1041]
IMHO this information is useless:

![grafik](https://user-images.githubusercontent.com/15329494/218449319-1d1d96e8-4e4b-4d6c-9ef5-10f64ad76fd3.png)

If we would be using apt directly someday then we could bring it back but who can have any plus in looking onto this weird packagekit output?

@madsrh @anasereijo ?

**Comment by d-loose** [comment]
The terminal output currently just shows the information received from [`ItemProgress`](https://www.freedesktop.org/software/PackageKit/gtk-doc/Transaction.html#Transaction::ItemProgress) events.
Since https://github.com/ubuntu-flutter-community/software/pull/944 the progress bar displays the percentage of the entire transaction (which is still broken down into 'download' and 'install' parts) rather than the individual events. We could show those event details here, maybe as an additional progress bar together with the current package name and the status, instead of dumping them into this terminal output.

**Comment by d-loose** [comment]
On second thought, it seems a bit redundant though - all the information, except for the progress of the individual events, is already shown above
