### ISSUE TITLE
Can't switch snap tracking channel without reinstalling

### ISSUE THREAD

**Issue by d-loose** [ubuntu-flutter-community/software#1069]
[Screencast from 2023-02-16 11-47-13.webm](https://user-images.githubusercontent.com/113362648/219344084-4d5e003f-b400-46a9-be8d-ff5ea10f5150.webm)

**Comment by Feichtmeier** [comment]
Is this possible with snapd?

**Comment by d-loose** [comment]
Yes, you can just pass a `channel` to `refresh`

**Comment by Feichtmeier** [comment]
yes ofc but then the whole snap is refreshed :)

the app should run refresh if you press the update button

**Comment by Feichtmeier** [comment]
ahhhh now I know what is happening there :)

refresh is run correctly here
https://github.com/ubuntu-flutter-community/software/blob/main/lib/services/snap_service.dart#L204

but since the version is the same the update button does not show up
if we want to move away from version checking here too we need to be careful to not break anything though.

**Comment by Feichtmeier** [comment]
I guess it is caused by this https://github.com/ubuntu-flutter-community/software/pull/1051/files 
-.- as I said, this whole construct is really fragile I've build there, because the refresh --list functionality was not there until now
I fix it until you land your PR
