### ISSUE TITLE
collection page: cancelling updates one by one

### ISSUE THREAD

**Issue by anasereijo** [ubuntu-flutter-community/software#1074]
I just noticed that when I click on [update (4)] I get asked to insert my password, but if I cancel, I have to **cancel four times** - maybe because it's 4 updates? 

(not so good recording, but I can provide a better one if needed :D)

[Screencast from 16-02-23 11_49_53.webm](https://user-images.githubusercontent.com/36884067/219358670-11be87ff-57d8-4904-becc-c44b686f87c8.webm)

**Comment by Feichtmeier** [comment]
snapd.dart does not have the option to refresh a bulk of snaps 
so we loop through the updates here and basically trigger each update 1 by 1
to not have the password prompt pop up so often I made the "trick" to update the first, then wait and update the rest because the auth is saved for some seconds. 

if snapd.dart will not have bulk refresh (including channel switch), I think we need to make this smarter in here. but I would love if snapd.dart could just provide this. if I understand snapd rest api correctly it should be possible to refresh a bulk of snaps

```
{
    "action": "refresh",
    "snaps": ["moon-buggy"]
}
```
