### ISSUE TITLE
Software closed for translation on Weblate

### ISSUE THREAD

**Issue by AsciiWolf** [ubuntu-flutter-community/software#1218]
It looks like it is not possible to translate [Software on Weblate](https://hosted.weblate.org/projects/ubuntu-software/ubuntu-software/). There is "The translation is temporarily closed for contributions" message displayed on the website.

**Comment by madsrh** [comment]
@kenvandine could you have a look at this? Seems like there's a merge conflict.

**Comment by d-loose** [comment]
I've taken a look at the merge conflict:
The problem is due to newly added, but empty ukrainian translation in fa49937ea43ba5cfee3dda626301d5b524e73e86
Deleting `lib/l10n/app_uk.arb` on the main branch should resolve the conflict - and allow weblate to successfully merge 303886e38574aee475fb97654862bada1134d942

**Comment by Feichtmeier** [comment]
should be fixed i think

**Comment by AsciiWolf** [comment]
Yep, it is fixed. I have already translated Ubuntu Software into Czech on Weblate. Thanks! :-)
