### ISSUE TITLE
SnapModel: localize install date tooltip

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#129]
![grafik](https://user-images.githubusercontent.com/15329494/187630095-1c3483e1-c930-49f0-8b88-b02f61336e2a.png)

I think it's not working as expected :) I'll dig in

_Originally posted by @Feichtmeier in https://github.com/ubuntu-flutter-community/software/issues/125#issuecomment-1232619586_

**Comment by oSoMoN** [comment]
> I think it's not working as expected

What is not working as expected? It looks correct to me, in the screenshot. What format did you expect for the tooltip?

**Comment by Feichtmeier** [comment]
The label correctly displays the localized date. The tooltip however doesn't. (German date)

**Comment by oSoMoN** [comment]
My intention was for the tooltip to display the timestamp in pseudo-[ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format, which is locale-independent. That's a pattern I've seen quite often on websites where hovering over a date/time displays this sort of tooltip. So that was behaving as I had intended it. But I'm open to suggestions on how to make this more user-friendly.

**Comment by Jupi007** [comment]
Personally, I would prefer a timestamp like you said @oSoMoN, but localized: `31-08-2022 12:50:00` for example.
It would be less confusing for end users, especially with beginners.
