### ISSUE TITLE
Language defaults to German (?) instead of English when missing translation

### ISSUE THREAD

**Issue by AdamSzopa** [ubuntu-flutter-community/software#216]
I'm using Ubuntu 22.04 in Polish, my locale is:

```
LANG=pl_PL.UTF-8
LANGUAGE=
LC_CTYPE="pl_PL.UTF-8"
LC_NUMERIC="pl_PL.UTF-8"
LC_TIME="pl_PL.UTF-8"
LC_COLLATE="pl_PL.UTF-8"
LC_MONETARY="pl_PL.UTF-8"
LC_MESSAGES="pl_PL.UTF-8"
LC_PAPER="pl_PL.UTF-8"
LC_NAME="pl_PL.UTF-8"
LC_ADDRESS="pl_PL.UTF-8"
LC_TELEPHONE="pl_PL.UTF-8"
LC_MEASUREMENT="pl_PL.UTF-8"
LC_IDENTIFICATION="pl_PL.UTF-8"
LC_ALL=
```

but when I launch the app, the UI language seems to be German (I think).

![language](https://user-images.githubusercontent.com/9355607/190625504-875799fc-443d-45cf-a1aa-8636edb61de0.PNG)

I expect the app to default to English if Polish is not aviable.

**Comment by Feichtmeier** [comment]
Hi @AdamSzopa :)
That would be a mistake ofc! Strange behavior indeed. It is danish though
If you are a polish speaker, could you eventually add polish translations?

**Comment by AdamSzopa** [comment]
Of course! :)

**Comment by jkerola** [comment]
I think this is caused by flutter_localizations defaulting to the first item on the supportedLocales list when the current platform locale is not on there. Since supportedLocales is automatically generated in alphabetical order, Danish takes priority at the moment [(see this issue for details).](https://github.com/flutter/flutter/issues/100857#issuecomment-1081876609)

If you don't mind, I'd like to take a shot at fixing this!
