### ISSUE TITLE
Debian package presentation

### ISSUE THREAD

**Issue by hsbasu** [ubuntu-flutter-community/software#287]
First of all, I really enjoy this piece of snap. A responsive design! really helps to cope up on tablet sized screens. Yeah! It really has become a store, a user can dream of. Almost everything I want from it is only at a click away. However, I also think there are a few aspects, which can be improved.

1. [ ] Cannot install from a deb source. For example, gimp is available both as snap and as deb package. However, when I went to install it from the store, I found only snap sources are available (Screenshot attached). It would be better, if we get an option to install from a deb repository.
![no_deb_src](https://user-images.githubusercontent.com/41947504/192446748-0cc9b93a-e605-4738-9287-35d6a1191ea3.png)

**Comment by Feichtmeier** [comment]
Hi @hsbasu - glad that you enjoy this app. Thanks for your feedback

The first point is more a design decision. 
I don't know if you have noticed, but the search result has two tabs: 1 for snaps, 1 for debs:

![grafik](https://user-images.githubusercontent.com/15329494/192458989-dd09164a-13ba-4951-b972-9958fdfed905.png)

So you can totally install gimp and any other deb :)
(The debs currently do not have meta data - see #128 )
You say "it would be better" - I know that it is like this in gnome-software, but I do not know if it would be really better or if we just learned that it is like this.
So I leave it to more design input from canonical if the package format should be hidden/abstracted
Could you create a dedicated issue for this? In general it would be better if you create not these "feedback" issues because they are hard to track/solve/process. Better 1 issue for 1 thing you would like to change.

The ratings is also a dedicated issue and it is under discussion if and how we want this in this app.

I have already hard times to answer your personal issue list. Could you break this issue into more issues please?

**Comment by hsbasu** [comment]
Sorry for trouble. Next time, I'll make sure to split them. As for the Deb packages, I observed two patterns.

1. When I **searched** for GIMP, I am getting two dedicated tabs one for snap and another for deb sources.
2. I browse for GIMP by going **Art and design>GIMP**. I get the one mentioned in the issue.

Can these two be merged?

**Comment by hsbasu** [comment]
@Feichtmeier Does it look fine now?

**Comment by Feichtmeier** [comment]
Yes much better! Thank you very much :) Like this we can track/process and prioritize issues :+1: 

You can close this one if you moved all issues

**Comment by hsbasu** [comment]
I guess this should not be closed yet due to this:


> ... As for the Deb packages, I observed two patterns.
> 
>     1. When I **searched** for GIMP, I am getting two dedicated tabs one for snap and another for deb sources. Just like you mentioned.
> 
>     2. When I browse for GIMP by going **Art and design>GIMP**. I get the one mentioned in the issue.
> 
> 
> Can these two be merged?

**Comment by Feichtmeier** [comment]
Oh you changed the issue description :+1: ok! :smiley: 

Yeah this is also a design question - IMO I would personally hide debs from the main exploration and show them if one searches for a specific name. Also because debian and snaps have **different names** (this one is really hard and I guess this is another reason for the previous gnome software based snap store rather bad search performance? CC @kenvandine )

**Comment by Feichtmeier** [comment]
Fixed
