### ISSUE TITLE
Monochrome spinner in nav rail

### ISSUE THREAD

**Issue by Jupi007** [ubuntu-flutter-community/software#646]
@Feichtmeier @madsrh What do you think of using a monochrome spinner in the nav rail:

| Current | Proposal |
| --- | --- |
| ![Capture d’écran du 2022-12-15 19-11-23](https://user-images.githubusercontent.com/36476595/207936144-12e2ec14-ec7a-4e8c-8f36-1d2d83e5079e.png) | ![Capture d’écran du 2022-12-15 19-11-03](https://user-images.githubusercontent.com/36476595/207936147-894564fa-ba14-47e7-9263-93f24d74171d.png) |

**Comment by madsrh** [comment]
As you've illustrated in darkmode, this works much better 👍

**Comment by Jupi007** [comment]
I added more screenshots in the linked PR #647 :)

**Comment by Feichtmeier** [comment]
TBH, I prefer the primary color spinner, as it indicates that this is an active progress : /

**Comment by Jupi007** [comment]
Honestly, I think that the fact there is a spinning loader, whatever its colour, shows progress.
I really don't like the orange one because it stands out and looks out of place among other monochrome icons. And btw, the transition between the monochrome icon and the coloured spinner is really not pretty.
Also, the contrast is a bit bad in the dark theme when the page is selected.

But if you don't like it, there is no problem 🙂

**Comment by Feichtmeier** [comment]
If the contrast is bad on the light grey then we need to change the colors and not make everything monochrome. I mean, if this is an argument we could not use color at all, never, under any circumstances

![](https://media.giphy.com/media/J1v0nIwwE8pHjGrjmj/giphy.gif)

**Comment by Feichtmeier** [comment]
I think that the flutter yaru dark theme is generally too bright. if we would change it to make it darker overall, all colors should profit from this having a better contrast on the dark theme

**Comment by Jupi007** [comment]
Honestly, the contrast argument is not the most important one for me 😅 I really hesitated to add it to the comment.
Imo, the main problem is that the orange spinner stands out. It looks out of place.
The monochrome version is very well integrated among the other icons.
I don't want to drop all the colours, but just have a consistent look 😉

But I can understand that you don't like it, as you have seen this coloured version for a long time.
BTW, did you try the branch? 🙂

**Comment by Feichtmeier** [comment]
it's not about not liking it, you have a valid point about the orange on the light gray, but I don't think that just removing the color from the spinner is the right solution

**Comment by Jupi007** [comment]
Please forget this thing of contrast 😅
It was really just a little thought I added at the last time when I wrote my comment.

My intention was initially to have an "icon" style spinner by using the same colour as them. What looks better in terms of design.

Currently, the orange makes this part of the nav rail a "hot spot" which is grabbing your attention too much on this specific part of the navigation.
Imo the accent should be kept for things like the badge, which is telling something important to the user: it requires an action from him, while check/install updates is a background action.

But honestly, my main motivation was the design. This monochrome version looks very good regardless of the coloured one, because it is consistent and integrated among the other nav items 🙂

**Comment by whiskeyPeak** [comment]
I personally feel like the lack of a prominent accent colour makes the current software centre feel a little gloomy, especially in dark mode. Maybe the navigation rail indicator could be a shade of orange to grab the attention of the user better?

**Comment by Feichtmeier** [comment]
Yes I'm also feeling this. We currently remove colour every where because of the old trauma of the Ubuntu orange sticking out but this will definitely move in the wrong direction. Especially @madsrh was really keen on removing primary colour everywhere but please let's stop this right now. It's a bad trend 📈😂

**Comment by Jupi007** [comment]
I totally agree with you @whiskeyPeak @Feichtmeier we miss some colours 💯

But so, we would need to unify the look of the rail. Do you want to make all selected item icon coloured? Or maybe make the selection background look like the GS quick toggle? Imo, this last proposal would be very nice. I will try this in yaru_widgets!

My only problem is not the colour itself of the spinner, but more the alien look among the fully monochrome nav rail icons. I just want it to be consistent 🙂

Each time I saw this spinner, I had the feeling that something was wrong. So, in the first time, I changed its size to be exactly the same as the other icons. It was better, but no suffisent. The last difference was the colour!

Imo each widget, which is placed in the icon place of the nav rail item, should mimic an icon as much as possible.
BTW, I'm also thinking about creating a named controller of the circular progress, which would return an iconny version, with the correct default size and colour.

_Another idea off topic: what do you think of showing the progress of updates install in the nav rail, with a determined progress indicator? 🤔_

**Comment by Jupi007** [comment]
What about something like this:

https://user-images.githubusercontent.com/36476595/208292462-c3501b58-bbec-4c7e-8857-4443b7cd75b8.mp4

This is colourful **and** consistent 🙂

**Comment by Feichtmeier** [comment]
This is not bad but ofc it changes the whole navigation

I still don't agree that a colorful spinner is by any means inconsistent

We use colour for several reasons:

- importance
- attention
- selection
- progress

In this navigation we use grey for selection
A colorful spinner means that there is progress and in this case also quite heavy computation happening right now: the packagekit monster clearing the cache, searching for updates and  getting the right group for every update.

I think this is one cool thing about flutter that you can just replace one widget with the other (except when it needs to implement an interface like PreferredSize)

Why is it inconsistent to replace a static icon with a colorful progress indicator when progress is happening right now?

**Comment by Jupi007** [comment]
Honestly, I prefer the current look of the nav rail selected item.

> Why is it inconsistent to replace a static icon with a colorful progress indicator when progress is happening right now?

It is inconsistent because all the other "icon" widgets in the nav rail are monochrome 🙂
It is not bad to be coloured, just a monochrome progress is really really much prettier from my point of view.
The simple spinning animation is already clearly show the progress idea to the user.

_But this opinion is really only restricted to the nav rail.
I love the coloured progress in any other part of the ui!_

And sorry to ask again, but did you tried for a while #647 ? 😀

**Comment by Feichtmeier** [comment]
Yes, I am sorry to say that I don't think this makes sense semantically and it looks almost inactive. 

The other icons are icons, this is a progress indicator. It is like saying an elevated button is inconsistent beneath an elevated button because it is not full coloured. But it is a different widget, with a different meaning, so I really can not get behind this argument of inconsistency

**Comment by Jupi007** [comment]
Okay, I understand 🙂
This is clearly make sense.

Let's close this so.

**Comment by Feichtmeier** [comment]
Eventually if we utilize the new appbar from JP, we could move the spinner to the appbar, with a popover showing what is happening?

**Comment by Jupi007** [comment]
Hmm, I don't know.
The actual place of the spinner clearly show that updates are installing.
Move this to the app bar would be maybe confusing for the user.

**Comment by madsrh** [comment]
I know this issue/PR is closed, but just wanted to add my 2 cent and as you properly have guessed I was +1 for the PR 😄 

> ...Especially madsrh was really keen on removing primary colour everywhere...

Not everywhere 😅 but I often find orange text and icons to look a little out of place. More color is great, but I don't agree that you need a colorful spinner to show that there's progress - IMO the animation of the icon is sufficient.

I like the idea of the progressbar, but I'll create a separate issue for that discussion, just to keeps things separated.

**Comment by Feichtmeier** [comment]
> Not everywhere 😅 but I often find orange text and icons to look a little out of place. 

Yeah I know that you do not like orange text and icons but we can not use this as an argument to remove semantic color randomly, sorry

**Comment by anasereijo** [comment]
@Zoospora any thoughts on this?

**Comment by Zoospora** [comment]
Happy New Year!

I've been reading the thread and would like to make some input on the matter:

Regarding the orange on dark grey colour (leaving aside the conversation about its semantics), the branding department has worked to ensure that there is sufficient contrast and accessibility depending on the chosen background colour (at least for graphical elements). In this sense, I agree with @Feichtmeier that it might be worthwhile (if you decide to take into account the semantic value) to opt for a background colour that favours accessibility. I think it is essential not to lose sight of accessibility as well as usability. 

Regarding semantics, from a point of view more related to the user experience (correct me if I'm wrong @anasereijo), I think it is necessary to warn the user in an efficient way about the process that is happening. Not being UX, I don't know how important this specific notification might be for the user (it would have to be investigated), but it certainly doesn't seem unreasonable to use orange when this spinner starts spinning.  

In case it helps, here are some examples of loading spinner patterns I've found on the web: many of them combine neutral grey with an accent colour. 

![image](https://user-images.githubusercontent.com/9861718/210367808-7933c00c-4d33-4dd3-91d1-b0468b11a801.png)
![image](https://user-images.githubusercontent.com/9861718/210367835-7943b3df-5765-41c1-a2a7-7dd7faf40406.png)
![image](https://user-images.githubusercontent.com/9861718/210367858-2e405b2b-a8df-4a07-af3d-e457b0825a57.png)

I understand that there may be opinions about the visual part (although I don't see any problems, since accent colours are used for this kind of things), but even so, I think that usability should not be dispensed with in order to make something more pleasing, but rather a solution should be found that fits and can solve both problems. I don't know if just that icon rotating in the same colour would be enough for the user to notice the action as it is subtle. 
 
It might also be worth exploring just in case the idea of creating different states for the icon that combine both solutions into one more similar to the ones shown above. 

Anyway, as I said, this is just my point of view. Let me know if you need anything. 

Thanks!!

**Comment by Jupi007** [comment]
Happy new year!

Just to be sure, I wanted to have a monochrome spinner, _only_ in the nav rail 🙂 In any other place this indicator should be accented ofc.

But I have no problem with the current look, just I think a monochrome version looks better in this precise location.

**Comment by Zoospora** [comment]
Thank you for your reply! 😊 I see, that's what I meant by my previous comment. 
Anyways, if you need anything, just let me know. Happy to help!

**Comment by Jupi007** [comment]
Thanks, that's fine so 😀
