### ISSUE TITLE
AppStream service initialization slows down search

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#663]
Currently the AppstreamService is loaded asynchronously and without awaiting the future inside app model init. 
The page loads but the appstream service is not ready yet, slowing down the initial search a lot (after this initial lag, everything is fine though) :cry: 

https://user-images.githubusercontent.com/15329494/208499167-759465cc-558e-440d-bf6e-fd87f22d3d32.mp4

________

## Solution A - await AppStreamService.init (10 seconds splash screen on EVERY start):

https://user-images.githubusercontent.com/15329494/208498539-d133ff14-a5e1-4089-a50c-146c9db19113.mp4

## Solution B - do not select select debian packages initially as selected AppFormats:

https://user-images.githubusercontent.com/15329494/208497825-66d5aa3c-919d-4ec6-863c-e5b8a1fee7ef.mp4

## Solution C - make appstream service init faster (lol) and await the service

@jpnurmi @d-loose any ideas?

**Comment by d-loose** [comment]
In principle I like Solution B, but it would be nice if debian packages were automatically added to the selected `AppFormat`s (and search results updated accordingly) as soon as `AppstreamService` is done with its initialization.
Since it takes quite long there should definitely be some indication to the user.

Semi-related: If you start typing a search query quickly enough, you end up on the `SearchPage` before `SnapService` has finished loading its sections and the page gets redrawn every time it loads the next one (causing the flickering in your screen recording).

**Comment by Feichtmeier** [comment]
@d-loose hm hm, now the store starts, but then it takes 10-15 seconds to finish the UI because it is still waiting for the appstream service :cry: 


https://user-images.githubusercontent.com/15329494/210669579-3ad421c0-b410-4eee-a743-0c931b43dfac.mp4

**Comment by Feichtmeier** [comment]
But this made me think of the whole page flow again since on the start page are only snaps anyways. I open a discussion

**Comment by d-loose** [comment]
The problem is that `ExploreModel` is now initialized before `PackageService` finishes connecting to `PackageKitClient`. Since #650 `PackageService` provides a `serviceAvailable` attribute, which defaults to `false` and is asynchronously updated if the connection can be established without errors. But it currently lacks a way of communicating that its availability has changed.

**Comment by Feichtmeier** [comment]
Ok I try to disconnected the pages more from each other and ping back when I am done?
We are currently also discussing a different page flow which needs a navigator

**Comment by d-loose** [comment]
Ok, sounds good.
It would also be great to find a way to test these kind of dependencies without making too many assumptions on the page flow :)

**Comment by Feichtmeier** [comment]
@d-loose ok done :) maybe you could re-investigate if you have time now
