### ISSUE TITLE
Show amount of updates and progress in the Ubuntu dock

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#687]
It would be nice to use this unity7 ubuntu dock / plank API to show the amount of updates + progress bar on updating in the ubuntu dock

![grafik](https://user-images.githubusercontent.com/15329494/210580949-98ebabbd-6d18-47e3-962c-065ba65a4135.png)

I have no idea how this works though :shrug: 

@3v1n0 maybe and idea? :)

**Comment by madsrh** [comment]
I really like this idea 👍 

Wouldn't you also want the progressbar in the app sidebar?

<img width="444px" src="https://user-images.githubusercontent.com/3986894/211146049-44f407b6-a4b8-464a-8d14-e426cb66e2db.gif">

**Comment by Feichtmeier** [comment]
hm either badge or bar
we could show the badge after check if the check found updates. when the updates are running we could only show the bar then

**Comment by d-loose** [comment]
I've started working on a package for this - https://github.com/d-loose/launcher_entry .
I'll polish it a bit and include it in the software store after the weekend :)

**Comment by Feichtmeier** [comment]
Thanks Dennis 😊 and have a nice weekend

**Comment by Feichtmeier** [comment]
Instead of creating yet another issue without context I thought  I could open it up again.

There is room for improvement. The badge and progress bar show and hide in flashes:

https://user-images.githubusercontent.com/15329494/215089510-7c3c41e1-fb72-466a-bef4-f422fc4c8b67.mp4

- the bade could be hidden when the updates are running
- the flashing could be improved by showing a 0 value so the bar does not hide and show again?

**Comment by d-loose** [comment]
I think I misunderstood how the Launcher API's `Update` function works. It seems like the status of the launcher icon is overridden rather than updated, when calling the function repeatedly (e.g. if you call `update(count: 10, showCount: true)` followed by `update(progress: 99, showProgress: true)` it will hide and the counter badge again, instead of just adding the progress bar.
But I guess `launcher_entry.dart` should reflect the behavior of the DBus API, so I'd rather not change it there by adding some caching of the values and instead do it here.
