### ISSUE TITLE
Change the "All apps" icon

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#74]
The compas icon 🧭 used next to **All apps** should not be a compas.

It looks a bit odd that it's placed next to the same icon in the sidebar. More importantly, I associate the compas with exploring something, but here it should illustrate that all categories are searched. I don't really have a good idea for an "all" icon.
Don't know if the magnifier glass 🔍 (like we had earlier) would be better 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/3986894/182569029-371daf01-3ed9-4637-a3e5-117f7cf01ecf.png)

**Comment by Jupi007** [comment]
Maybe could you use the `app_grid` icon here?

![](https://raw.githubusercontent.com/ubuntu/yaru_icons.dart/master/icons/app-grid.svg)

**Comment by Feichtmeier** [comment]
app grid sounds like the better choice because the search icon does not indicate that you can click the icon to select a category

The category/section filter changes the displayed grid of apps and also enables the specific filter in which the input is searched
![grafik](https://user-images.githubusercontent.com/15329494/183242193-5bd22c94-bc76-497a-8f68-7c3b796a888f.png)
![grafik](https://user-images.githubusercontent.com/15329494/183242206-f4b7fce2-0643-45bb-8adb-03c90feedeed.png)
