### ISSUE TITLE
New fallback icon

### ISSUE THREAD

**Issue by anasereijo** [ubuntu-flutter-community/software#798]
@Zoospora is currently working on a few proposals for a new 'Canonical' fallback icon. It will go to snapcraft.io, charmhub, and other places where we use them. I think she is gathering feedback from the brand/design team, so hopefully we will have a proposal soon. :)

**Comment by anasereijo** [comment]
@Feichtmeier not sure if I picked the correct label, feel free to change it if not :D

**Comment by Feichtmeier** [comment]
Cool! As soon as we got this one we can exchange it here as well :)

**Comment by Jupi007** [comment]
This is related to: https://github.com/ubuntu/yaru_widgets.dart/issues/396

**Comment by Zoospora** [comment]
Hey!  I'm still working on the proposals. We are indeed iterating on the design to try to come up with a proposal that can work well for the different products and align the designs we have.  As soon as it is ready, I will send it to you. Thanks for your patience!! 😊

**Comment by Zoospora** [comment]
Hey all!
After a few days in which we have considered different proposals, finally the team has decided to update the fallback Icon of the different stores in which, without modifying its simplicity, the brand is represented in a more updated way. 
So, this is the proposal that I am presenting to you. I attach a couple of examples of how it would look in the different themes:

![image](https://user-images.githubusercontent.com/9861718/213645491-f09756da-ef6f-46c0-8619-ab304e5a495e.png)

![image](https://user-images.githubusercontent.com/9861718/213645529-16871d6d-564e-4315-b38c-a6580a9b4910.png)

![image](https://user-images.githubusercontent.com/9861718/213645548-a53017a1-d63c-4be2-b5d6-27d9abeaa7d2.png)

Although the change is subtle, it is in line with the new "3d" Suru that we are using in some of the new designs:

![image](https://user-images.githubusercontent.com/9861718/213645614-e56e26db-6b3d-44e0-98c0-ee2190712298.png)

If you consider it suitable for use, please let me know the best way to get it to you, format, etc.
Thank you very much for your patience and work!

**Comment by Feichtmeier** [comment]
Thanks @Zoospora 👍

Do you mind if we create a dark version for this for the dark theme?

**Comment by Zoospora** [comment]
How about something like this? I've tried to keep the contrast level between the background and the icon at a similar level.

![image](https://user-images.githubusercontent.com/9861718/213670330-3a241053-f52a-4357-9352-01284da212ac.png)

![image](https://user-images.githubusercontent.com/9861718/213670431-e0138032-cbb6-4741-bd4e-8cc50b3b4ad8.png)

![image](https://user-images.githubusercontent.com/9861718/213670465-4d9db6bf-1682-416b-b907-11a6c2f36f12.png)

Thanks!

**Comment by Jupi007** [comment]
Thanks @Zoospora 

The design is great :+1: 

I think more emphasis should be on the subtle differences in opacity between the different elements of the icon.
On your proposal, at a first look, it looks like there is only two elements.
We could play with opacity like this (I did it quickly):

![image](https://user-images.githubusercontent.com/36476595/213670196-1069e939-f854-4dff-8169-76ae946a43d4.png)

**Comment by Jupi007** [comment]
> How about something like this? I've tried to keep the contrast level between the background and the icon at a similar level.

It looks pretty good :+1:

**Comment by Feichtmeier** [comment]
Great design @Zoospora

**Comment by Zoospora** [comment]
Thanks @Jupi007, great feedback and proposal! 
 
I understand your opinion and from the department in fact different proposals were made with more detailed shapes but all of them seemed too elaborate to be used in other contexts (as in situations where it is surrounded by too many graphic elements it adds visual noise). 

Since we are working on the alignment of different elements, we had to find an optimal solution that could work in all scenarios. That's why we tried to simplify.

We will use this version in the other stores as it is the one that has been finally approved. It would be great to be aligned and with that intention we have also proceeded to create the dark mode version. In order to try to meet the essential requirements of each of the stores. 

What do you think? 

Thanks again for the feedback and suggestions 😊

**Comment by Feichtmeier** [comment]
Ok! I think it would be best to recreate those icons with flutter so we do not need to load assets, which takes time.
Shall I do this with my container fun in software or do you want to tackle this with cutom painters in yaru widgets @Jupi007 ?

**Comment by Jupi007** [comment]
@Feichtmeier I will implement this with a custom painter in yaru_widgets. It is not animated, so it shouldn't be very complicated to do :)

@Zoospora I understand that you mean and I agree :+1: 
Can you provide some resources to help me in the implementation of this: svg for points and some colours, on which I can base my work to be as precise as possible?

**Comment by Zoospora** [comment]
Of course! And thanks for understanding 😊
Here is the list of colours in hexadecimal and hsl:

**Light theme:**

    **Background:**
    #C8C7C7 / 0,1,78

    **Details:**
    #D9D9D9 / 0,1,85
    #EEEDED / 0,1,93

---

**Dark theme:**

    **Background:**
    #5C5C5C / 0,0,36

    **Details:**
    #737373 / 0,0,45
    #616161 / 0,0,38

--- 
![Light Theme](https://user-images.githubusercontent.com/9861718/213687411-7b8295d9-bdf1-4cba-8010-0f468000cc27.svg)
![Dark Theme](https://user-images.githubusercontent.com/9861718/213687421-c56996e9-6fed-4777-ad13-89852881b63a.svg)

I don't know if it's enough to upload the svg here or if you prefer me to send it somewhere else. 

Thanks!

**Comment by Jupi007** [comment]
Thanks a lot @Zoospora 
This is enough for me to start to work on this :)

**Comment by Zoospora** [comment]
Thanks to you!
PS: It looks weird when previewing it on the web but apparently there is no problem in Illustrator or Figma. Let me know if there is a problem.

**Comment by Jupi007** [comment]
No problem, I just need some reference coordinates on which I can base my work :)

**Comment by Jupi007** [comment]
I just finished to implement this icon design into yaru_icons: https://github.com/ubuntu/yaru_icons.dart/pull/119

**Comment by Jupi007** [comment]
The placeholder works well in app card:

![Capture d’écran du 2023-01-24 11-31-38](https://user-images.githubusercontent.com/36476595/214269313-2cb61db9-7557-4250-9434-54d58a523684.png)
![Capture d’écran du 2023-01-24 11-31-21](https://user-images.githubusercontent.com/36476595/214269317-8621c029-f742-466e-971c-8897aa2c7ac7.png)

But it is broken in the banner:

![Capture d’écran du 2023-01-24 11-32-07](https://user-images.githubusercontent.com/36476595/214269394-cf18760a-0e4d-4a24-a904-f30fbf5c88fd.png)

It is caused by a different size between the one given to the widget, and the sized box around it which is smaller.
In fact this is a problem on the placeholder widget side because it should adapt itself to its environment.

**Comment by Jupi007** [comment]
😅 Nevermind, there is the same problem if I simply use an `Icon`:

![image](https://user-images.githubusercontent.com/36476595/214271222-8ceba5ce-9443-4201-9af4-bc565106774c.png)

I will fix that here so :)
