### ISSUE TITLE
Searchbar look

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#803]
I just noticed that I only tested the new look in https://github.com/ubuntu-flutter-community/software/pull/753 with the dark theme 🙈 I would like to suggest a white background for the light theme and a very subtle border. WDYT?

This sounds simple and maybe I could even make a PR, but now... 2 hours later, after trying every possible `fillcolor` I could think of, it's not that simple 😄💩 

![image](https://user-images.githubusercontent.com/3986894/212775535-b3a87c52-4d42-4459-b151-7d6b9ce74725.png)

**Comment by Feichtmeier** [comment]
Yeah it is indeed not that simple because textfields either have the border style or the fill style. I also don't think that this looks good or fitting. Neither does only a white bg look IMHO:
![grafik](https://user-images.githubusercontent.com/15329494/212844284-68292043-5fe9-449b-b2ba-08b74f0712d0.png)
Sticks out way too much.  The current grey fits better to the titlebuttons also.

**Comment by anasereijo** [comment]
FYI @Zoospora and I are looking into this!

**Comment by anasereijo** [comment]
@Zoospora and I had a chat about this, and we think the white input (preferably with a border) works best. 

One of the reasons is that we think that the dark grey version looks disabled. 

Aesthetically, we also think the white version has nicer contrast, it makes it look cleaner and more modern.
Sticking out is actually a good thing, as it is one of the primary functions of the application.

**Comment by Jupi007** [comment]
Personally, I also prefer the white search input :+1:

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/213295241-993e84d0-10a2-4244-82c1-0bb4ae770b23.png)
![grafik](https://user-images.githubusercontent.com/15329494/213295367-c568c659-4043-4ae4-8083-1e0ceaaaa3bd.png)

I like this search icon / clear icon alignment. When you enter the search bar the X icon appears

**Comment by Feichtmeier** [comment]
But since you all want it, you shall have it :smile: 
![grafik](https://user-images.githubusercontent.com/15329494/213317359-baff9ad4-8e1c-47ad-978e-eff353f6dbd6.png)
![grafik](https://user-images.githubusercontent.com/15329494/213317377-9ab51205-dcb7-4518-875a-ff2b3ba7fc2b.png)

But let's please keep the current look for the dark theme, :pray: 
![grafik](https://user-images.githubusercontent.com/15329494/213317422-b795ed7f-0aa5-4bfb-aeab-e14e17815632.png)
![grafik](https://user-images.githubusercontent.com/15329494/213317435-eb176f87-2dc7-49ac-8e2e-9e6561930b6f.png)

**Comment by madsrh** [comment]
> But let's please keep the current look for the dark theme, 🙏

The dark theme looks great (and now the light theme too 😅 ) 

> I like this search icon / clear icon alignment. 

I'm in doubt about the position of the search icon and so is Microsoft it seems. Sometimes it left, sometimes it right in Windows. I don't have strong feeling about this.

![image](https://user-images.githubusercontent.com/3986894/213318770-ce047743-c1ad-4141-a998-904fad4574cd.png)

**Comment by anasereijo** [comment]
> I like this search icon / clear icon alignment. When you enter the search bar the X icon appears

that is quite nice indeed!

**Comment by anasereijo** [comment]
> But since you all want it, you shall have it 😄
> But let's please keep the current look for the dark theme, 🙏 

Looks great on both themes, thanks for making the changes @Feichtmeier
