### ISSUE TITLE
Title alignment

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu-flutter-community/software#895]
I'm not sure what's best to have centered/aligned in relation to what but it would be nice to have a consistent alignment between pages. :)

![image](https://user-images.githubusercontent.com/140617/215101220-8ebf5bf4-69b6-49a0-8d22-e7748195caad.png)

**Comment by madsrh** [comment]
> it would be nice to have a consistent alignment between pages. :)

Yes! 💯

The blue lines are centered without including the sidebar. I prefer centering in relation to the entire width of window.

WDYT @anasereijo ?

**Comment by Feichtmeier** [comment]
indeed! this looks weird

**Comment by anasereijo** [comment]
> The blue lines are centered without including the sidebar. I prefer centering in relation to the entire width of window (like search)

Just had a quick look and, on bigger windows, seems that the search isn't actually centred in relation to the entire window or even with the 'content' section. On smaller windows, seems to be almost centred with whole window, though 🤔 is this because it's responsive? We should be able to align it always, right?

<img width="1273" alt="Screenshot 2023-01-27 at 15 06 15" src="https://user-images.githubusercontent.com/36884067/215118895-ab6fad52-89b8-41d1-8fe9-756308d593b9.png">

I agree that we should center search and titles in relation to the whole window, looking like this:

<img width="1218" alt="Screenshot 2023-01-27 at 15 19 35" src="https://user-images.githubusercontent.com/36884067/215121797-b7af8edd-f3a8-4d42-ab9c-4e9d5c07ed1f.png">

One more thing that might be off-topic, but it is related to alignments, is that I feel that the current alignment of the 'Ubuntu Software' label looks a bit weird, making it look unbalanced. I think it could be left aligned with the side nav items, making it look tidier (it would look even better if we could reduce the width of that side nav as @local-optimum proposed)

<img width="1511" alt="Screenshot 2023-01-27 at 15 26 33" src="https://user-images.githubusercontent.com/36884067/215123985-9d9d9d63-c0e1-4289-bd0b-c3abb185bd0e.png">

**Comment by Jupi007** [comment]
I agree that the left pane width can be reduced. But about the "ubuntu software" label, imo we should keep it centred, because 100% of the titlebar labels are centred in ubuntu.

**Comment by madsrh** [comment]
> One more thing that might be off-topic, but it is related to alignments, is that I feel that the current alignment of the 'Ubuntu Software' label looks a bit weird, making it look unbalanced. I think it could be left aligned with the side nav items, making it look tidier

That is a different topic @anasereijo 😅 We can move this to a new issue or a discussion? 

I agree that the title/name makes it look a bit unbalanced. THB, I think we should just remove the title. It's not like Firefox, Nautilus, TextEditor, Terminal or Calculator adds a title, because the app name is already in the top bar. It just seems redundant IMHO.
<img width="968" alt="image" src="https://user-images.githubusercontent.com/3986894/215130562-afe5bc8f-7723-4d30-97b3-e883c40c5d64.png">

**Comment by anasereijo** [comment]
> That is a different topic @anasereijo 😅 We can move this to a new issue or a discussion?

done! created a new [issue](https://github.com/ubuntu-flutter-community/software/issues/912) for that

**Comment by madsrh** [comment]
> created a new issue for that. we can now focus on the original issue 😀

Thank you for that @anasereijo. I just meant if we needed to have a long discussion about this, but it looks like everyone is on the same page here 👍😄 

I could spend a few hours removing the text and maybe (if I'm lucky) also the separator. So, @jpnurmi would you mind looking at this (also)? It'll take you one minute if you're already looking at the alignment.

**Comment by jpnurmi** [comment]
Hey, I've been busy with too many other things so I haven't really looked into this. I wanted to bring it up because it caught my attention when running the app. :) From a technical perspective, it could be nice to have just one top-level window title bar and control its content from the pages instead of creating a separate window title bar for every page. This would eliminate the opinionated separator, exclude the window title bar from page transitions, and center the title along the window. One could use an animated switcher for the plain window title label vs. a search box...

**Comment by Feichtmeier** [comment]
> Hey, I've been busy with too many other things so I haven't really looked into this. I wanted to bring it up because it caught my attention when running the app. :) From a technical perspective, it could be nice to have just one top-level window title bar and control its content from the pages instead of creating a separate window title bar for every page. This would eliminate the opinionated separator, exclude the window title bar from page transitions, and center the title along the window. One could use an animated switcher for the plain window title label vs. a search box...

Agreed. We should make a big restructure of the code.

**Comment by Feichtmeier** [comment]
@jpnurmi if you got time to help me with the tests, I can tackle the refactoring/moving. I am annoyed by the hierarchy since quite some time.

Plan:
- make searchQuery and selectedSection parameters of SearchPage and make SearchPage model-free (tm)
- move appbars and scaffolds out of all pages
- place the appbar in a scaffold inside _App
- move the search functions and getters out of explore model into appmodel and let _App pass searchQuery and selectiedSection to the lower pages

does this sound okay for you?

**Comment by jpnurmi** [comment]
This is like discussing the details of rewriting a book I haven't read but sounds promising in principle! :grinning:

**Comment by Feichtmeier** [comment]
Lol 😂
Yeah maybe I try to split this into tiny tasks first
