### ISSUE TITLE
Design discussion: explore page

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#91]
(click to enlarge)

## Explore Page

| Light | Dark |
|-|-|
|![grafik](https://user-images.githubusercontent.com/15329494/185951846-e768963a-cdfb-4c09-bf80-6364f5230d14.png)|![grafik](https://user-images.githubusercontent.com/15329494/185951951-41636428-d446-4020-b7ac-97d4a1137f49.png)|

## Large window

![grafik](https://user-images.githubusercontent.com/15329494/191794821-e9a65bb6-b5d3-413c-aa3a-ad8070efd4cf.png)

## Small window

![grafik](https://user-images.githubusercontent.com/15329494/191794748-74bd30a8-f1ba-4f3c-9217-70d0c555c908.png)

## Search

![explore_search_01](https://user-images.githubusercontent.com/15329494/185956381-8d1235fb-5f14-43c9-817e-26b901e2f52b.png)
![explore_search_02](https://user-images.githubusercontent.com/15329494/185956385-13ebbfea-30f4-425b-9335-d171ec459d32.png)

**Comment by mivoligo** [comment]
Great job guys with the app!
Just started looking at these beautiful screenshots. I hope you don't mind if I add some feedback from time to time :slightly_smiling_face: 

So here goes the first one:
As long as I remember I always wanted to have a "Start" or "Open" button in a software center on an app's page. It would be useful for example after installing a new app. Here I can see there is such a button but IMO is not enough exposed and I thought it was just a button to go to the program's website. So personally I'd love to see a nice big button (as big as "Install") somewhere next to the app's title/icon row.

**Comment by mivoligo** [comment]
Second one:
What if go fancy on an app's thumbnail and add one more line of description and even a screenshot?

**Comment by mivoligo** [comment]
I'd also vote for removing the "show more" buttons for Description and details with the version and such. Instead just show them to the user without extra clicking.

**Comment by madsrh** [comment]
@mivoligo You can edit your comment rather than create a new post 😉 

Great idea with the "Open/Start/Run/Launch/..." button 👍 

> What if go fancy on an app's thumbnail and add one more line of description and even a screenshot?

I agree that it would be great if the entire app tag line would fit. Most of them are short (like mailstring, notepadqq, slack) and that it properly the length we should aim for.
I'm not a fan of the screenshot idea, as this would add too much clutter IMHO. We could add some additional information on hover, but IMO that's unnecessary because opening the explanation dialog is so blazing fast.

@Feichtmeier would it be possible to add the _Verified Account_ badge? (poor mockup below) and ofc later a filter option for that, but I think we'll have to rethink that part 😃 (perhaps in november?)
![image](https://user-images.githubusercontent.com/3986894/188980132-fa0d16dc-6d46-45d4-bbe3-05b26689319d.png)

> I'd also vote for removing the "show more" buttons for Description and details with the version and such. Instead just show them to the user without extra clicking.

I'm not a fan of the "Show more" button either, but some apps have really long descriptions (like Xonotic) and here it would be highly annoying if the user have to scroll down to get to the install button. We will/should do this  explanation dialog section differently in the future.

**Comment by mivoligo** [comment]
Sorry for the spam :slightly_smiling_face: 

> I'm not a fan of the "Show more" button either, but some apps have really long descriptions (like Xonotic) and here it would be highly annoying if the user have to scroll down to get to the install button.

I'd imagine the install button (and some other parts of that page) not to be scrollable. 

The badge is very nice but I'd say it means "installed" if I haven't read the post ;)

**Comment by d0od88** [comment]
Can I ask what the design justification is for putting the single most important action of a software store — i.e. the install button, progress indication during installing, button to open (depending on install state) — at the bottom of the dialog?

**Comment by Feichtmeier** [comment]
> Can I ask what the design justification is for putting the single most important action in a software store — i.e. the install button/progress indication during install/button to open — at the _bottom_ of the dialog?

Hi 😊👋
This is all not set in stone
My intention with dialogues was that humans normally read from top to bottom
I've found gnome dialogues to be the only toolkit that puts such actions in the title, which I've personally always saw as unintuitive and strange. But in the end there is no such thing as intuitive UI and you need to learn it. Mouse travel on the other hand is a big factor to consider.
The information about the app is read from top to bottom. If you are done with reading you can use an action at the bottom

There will be big design input soon so eventually many things will change
Thanks for your input

**Comment by Feichtmeier** [comment]
this is outdated, I try to add a replacement somewhere
